---@meta
---@class SystemProps
---@field game_width number
---@field game_height number
---@field border_color table
---@field grid_size number
---@field rewind_data table
---@field rewind_step number
---@field old_rewind_step number
